# Generated by Django 5.0.6 on 2024-07-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('flame', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
